"""
Django settings for judge project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.join(BASE_DIR, 'judge')
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
SCRIPTS_DIR = os.path.join(BASE_DIR, 'scripts')
ETC_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'etc'))
VAR_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'var'))
LOG_DIR = os.path.join(VAR_ROOT, 'log')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b(#3^f2zujx_*!ua&9s7#5v!jf#_aa5lrhf1g002m%g6j9(ssn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
T_DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'config',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'judge.urls'

WSGI_APPLICATION = 'judge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIR = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


#------------uwsgi & nginx settings---------------
UWSGI_PROJECT_HOST = '127.0.0.1'
UWSGI_PROJECT_PORT = '11890'
UWSGI_PROJECT_SETTINGS_PATH = PROJECT_DIR
UWSGI_PROJECT_UWSGI_MODULE = 'django_uwsgi'
UWSGI_PROJECT_UWSGI_PROCESSES_COUNT = '4'
UWSGI_PROJECT_LOG_PATH = LOG_DIR

NGINX_SERVER_NAME='yourdaddy'
NGINX_LISTEN_PORT = '80'
NGINX_STATIC_EXPIRES = '2h'

#------------supervisor settings------------------


try:
    from local_settings import *
except:
    pass

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': T_DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },

    },
]